"""
seed_data.py
------------
The starter Declarative Knowledge Base + Rule Base for SmartRuleAI.

Each fact tuple is: (concept, statement, keywords, category, polarity)
  - category groups facts for the sidebar browser (passwords, network, ...)
  - polarity is "good" (protective), "risk" (dangerous), or "neutral"
    (used for the security checklist score and for chat-bubble coloring)

Each rule tuple is: (name, if_concept, then_concept, description)
  IF if_concept is known THEN then_concept becomes known (forward chaining).

Several chains intentionally converge on the same terminal concept
(e.g. "reduced_risk" or "account_vulnerable") so the reasoning engine can
demonstrate that more than one path can lead to the same conclusion.
"""

SAMPLE_FACTS = [
    # ---- Passwords & authentication -------------------------------------------------
    ("strong_password", "A strong password mixes uppercase, lowercase, numbers and symbols.",
     "strong password,complex password,secure password", "passwords", "good"),
    ("difficult_to_guess", "Difficult-to-guess passwords are hard for attackers to crack.",
     "difficult to guess,hard to guess,hard to crack", "passwords", "good"),
    ("better_protection", "Better protection reduces the risk of unauthorized account access.",
     "better protection,better account protection,improved security", "passwords", "good"),
    ("reduced_risk", "Reduced risk means the overall chance of a successful attack is lower.",
     "reduced risk,lower risk,safer account,improves security", "general", "good"),
    ("weak_password", "A weak password is short, common, or reused across sites.",
     "weak password,simple password,common password,reused password", "passwords", "risk"),
    ("easy_to_guess", "Easy-to-guess passwords can be cracked quickly by attackers.",
     "easy to guess,easily guessed,easily cracked", "passwords", "risk"),
    ("account_vulnerable", "A vulnerable account is at high risk of being compromised.",
     "account vulnerable,vulnerable account,account at risk,account compromised", "general", "risk"),
    ("two_factor_enabled", "Two-factor authentication adds an extra identity verification step.",
     "two factor,2fa,multi factor,mfa,two-factor authentication", "authentication", "good"),
    ("extra_security_layer", "An extra security layer makes unauthorized access much harder.",
     "extra security layer,additional layer,extra layer of security", "authentication", "good"),
    ("password_manager_used", "A password manager generates and stores strong, unique passwords.",
     "password manager,vault my passwords,lastpass,bitwarden,1password", "passwords", "good"),
    ("unique_passwords_per_site", "Using a unique password per site stops one leak from exposing every account.",
     "unique password,different password for each,no password reuse", "passwords", "good"),
    ("biometric_auth_enabled", "Biometric login (fingerprint/face) confirms it's really you before granting access.",
     "biometric,fingerprint login,face id,face unlock", "authentication", "good"),
    ("strong_identity_verification", "Strong identity verification makes impersonating the account owner very hard.",
     "strong identity verification,verified identity", "authentication", "good"),
    ("security_questions_weak", "Security questions with guessable or publicly known answers are easy to bypass.",
     "security question,mother's maiden name,pet's name,easy security question", "passwords", "risk"),

    # ---- Network -----------------------------------------------------------------
    ("public_wifi_used", "Public Wi-Fi networks are often unencrypted and unsecured.",
     "public wifi,public wi-fi,open network,free wifi,coffee shop wifi", "network", "risk"),
    ("data_interception_risk", "Unencrypted networks allow attackers to intercept transmitted data.",
     "data interception,intercept data,man in the middle,eavesdrop", "network", "risk"),
    ("vpn_used", "A VPN wraps your traffic in an encrypted tunnel before it leaves your device.",
     "vpn,virtual private network,use a vpn", "network", "good"),
    ("encrypted_traffic", "Encrypted traffic can't be read even if it is intercepted.",
     "encrypted traffic,traffic is encrypted", "network", "good"),
    ("firewall_enabled", "A firewall filters network traffic and blocks unsolicited connections.",
     "firewall,enable firewall,firewall enabled", "network", "good"),
    ("blocked_unauthorized_traffic", "Blocking unauthorized traffic stops many remote attacks before they start.",
     "blocked unauthorized traffic,blocks intrusions", "network", "good"),
    ("https_used", "HTTPS encrypts the connection between your browser and the website.",
     "https,ssl,secure site,padlock icon,tls", "network", "good"),
    ("encrypted_in_transit", "Data encrypted in transit can't be read while travelling across the network.",
     "encrypted in transit,protected in transit", "network", "good"),
    ("strong_wifi_encryption", "WPA3/WPA2 encryption on a home router keeps nearby devices from reading your traffic.",
     "wpa3,wpa2,wifi encryption,router encryption", "network", "good"),
    ("network_protected", "A protected network is much harder for outsiders to snoop on or join.",
     "network protected,protected network", "network", "good"),
    ("outdated_software", "Software that hasn't been updated is missing recent security patches.",
     "outdated software,haven't updated,old version,skipping updates,not updated", "updates", "risk"),
    ("vulnerabilities_exposed", "Exposed vulnerabilities give attackers a known, documented way in.",
     "vulnerabilities exposed,exposed vulnerability,unpatched", "updates", "risk"),

    # ---- Malware & devices ---------------------------------------------------------
    ("antivirus_installed", "Antivirus software detects and blocks known malicious programs.",
     "antivirus,anti-virus,security software", "malware", "good"),
    ("malware_protected", "Malware protection reduces the chance of system infection.",
     "malware protected,protected from malware,malware protection", "malware", "good"),
    ("software_updated", "Updated software includes the latest official security patches.",
     "software updated,update software,latest updates,patched software", "updates", "good"),
    ("vulnerabilities_patched", "Patched vulnerabilities cannot be easily exploited by attackers.",
     "vulnerabilities patched,patched vulnerabilities,no known exploits", "updates", "good"),
    ("usb_untrusted_used", "Plugging in an unknown USB drive can silently install malware.",
     "unknown usb,untrusted usb,found usb drive,random usb stick", "malware", "risk"),
    ("device_infected", "An infected device can steal data, spy on you, or spread to other machines.",
     "device infected,infected with malware,got a virus", "malware", "risk"),
    ("ransomware_attack", "Ransomware encrypts your files and demands payment to unlock them.",
     "ransomware,ransomware attack,files were encrypted by attacker", "malware", "risk"),
    ("data_encrypted_by_attacker", "Files encrypted by an attacker are inaccessible until you pay or restore a backup.",
     "attacker encrypted my files,locked out of my files", "malware", "risk"),
    ("iot_default_password", "Smart devices left on their factory-default password are trivial to break into.",
     "default password,iot device,smart device,factory password", "malware", "risk"),
    ("device_vulnerable", "A vulnerable device can be hijacked and used as an entry point into your network.",
     "device vulnerable,vulnerable device,device compromised", "malware", "risk"),

    # ---- Data & privacy --------------------------------------------------------
    ("data_encrypted", "Encrypting stored data keeps it unreadable to anyone without the key.",
     "encrypt my data,data encrypted,disk encryption,encrypted storage", "data", "good"),
    ("data_protected_at_rest", "Data protected at rest stays unreadable even if the storage device is stolen.",
     "protected at rest,data at rest", "data", "good"),
    ("regular_backups", "Regular backups mean you always have a safe, recent copy of your data.",
     "regular backups,automatic backup,i backup my data,cloud backup,back up my files", "data", "good"),
    ("data_recoverable", "Recoverable data means an attack or a failure doesn't mean permanent loss.",
     "data recoverable,can restore my data", "data", "good"),
    ("no_backups", "Without backups, a single incident can wipe out your files for good.",
     "no backups,don't backup,not backing up,never back up,no backup", "data", "risk"),
    ("data_loss_risk", "A high data-loss risk means one bad event could destroy irreplaceable files.",
     "data loss risk,risk of losing data,could lose everything", "data", "risk"),
    ("encrypted_messaging_used", "End-to-end encrypted messaging keeps conversations private from eavesdroppers.",
     "encrypted messaging,end to end encryption,signal app,whatsapp encryption", "privacy", "good"),
    ("private_communication", "Private communication can't be read by your provider or anyone in between.",
     "private communication,protected conversation", "privacy", "good"),
    ("excessive_app_permissions", "Apps with more permissions than they need can quietly harvest personal data.",
     "excessive permissions,app asks for too much access,over-permissioned app", "privacy", "risk"),
    ("privacy_exposed", "Exposed privacy means personal data may be collected, sold, or leaked without consent.",
     "privacy exposed,privacy at risk,exposed personal data", "privacy", "risk"),

    # ---- Social engineering & phishing --------------------------------------------
    ("phishing_email_received", "A phishing email tries to trick the user into revealing information.",
     "phishing,phishing email,suspicious email,fake email", "social", "risk"),
    ("credentials_at_risk", "Credentials shared through phishing or scams can be stolen by attackers.",
     "credentials at risk,stolen credentials,compromised login", "social", "risk"),
    ("social_engineering_call", "A caller pretending to be from support or the bank is a classic social-engineering attack.",
     "social engineering,scam call,fake tech support,vishing", "social", "risk"),
    ("impersonation_risk", "Impersonation risk means an attacker may successfully pose as someone you trust.",
     "impersonation risk,pretending to be someone", "social", "risk"),
    ("security_awareness_training", "Security awareness training teaches people to recognize common attack patterns.",
     "security training,awareness training,phishing training,security education", "social", "good"),
    ("spot_suspicious_messages", "Being able to spot suspicious messages stops most phishing attempts before any harm.",
     "spot suspicious messages,recognize phishing,notice a scam", "social", "good"),
    ("credentials_protected", "Protected credentials can't be handed over even when a scam attempt is made.",
     "credentials protected,login protected", "social", "good"),

    # ---- Mobile & physical ----------------------------------------------------------
    ("public_charging_used", "Public USB charging stations can be rigged to steal data (\"juice jacking\").",
     "public charging station,airport charger,public usb charger", "mobile", "risk"),
    ("juice_jacking_risk", "Juice jacking lets a compromised charging port copy data from your phone.",
     "juice jacking,charger data theft", "mobile", "risk"),
    ("data_theft_risk", "A high data-theft risk means personal information could be copied without consent.",
     "data theft risk,risk of data theft,data could be stolen", "mobile", "risk"),
    ("physical_device_unlocked", "A phone or laptop left unlocked lets anyone nearby access it directly.",
     "left unlocked,unlocked phone,unlocked laptop,no screen lock", "physical", "risk"),
    ("unauthorized_physical_access", "Unauthorized physical access bypasses almost every remote security control.",
     "physical access,someone accessed my device,walked away with my laptop", "physical", "risk"),

    # ---- Planning ------------------------------------------------------------------
    ("incident_response_plan", "An incident response plan sets out exactly what to do the moment something goes wrong.",
     "incident response plan,response plan,what to do if hacked", "planning", "good"),
    ("faster_recovery", "Faster recovery limits how much damage an incident can ultimately cause.",
     "faster recovery,quicker recovery,minimize downtime", "planning", "good"),
]

SAMPLE_RULES = [
    # Passwords
    ("Strong Password Rule", "strong_password", "difficult_to_guess",
     "IF a password is strong THEN it is difficult to guess."),
    ("Guessability Rule", "difficult_to_guess", "better_protection",
     "IF a password is difficult to guess THEN it provides better account protection."),
    ("Protection Rule", "better_protection", "reduced_risk",
     "IF an account has better protection THEN the overall risk is reduced."),
    ("Weak Password Rule", "weak_password", "easy_to_guess",
     "IF a password is weak THEN it is easy to guess."),
    ("Weak Security Question Rule", "security_questions_weak", "easy_to_guess",
     "IF security questions are weak THEN the account is effectively easy to guess."),
    ("Guess Risk Rule", "easy_to_guess", "account_vulnerable",
     "IF a password is easy to guess THEN the account becomes vulnerable."),
    ("Password Manager Rule", "password_manager_used", "unique_passwords_per_site",
     "IF a password manager is used THEN every site gets a unique password."),
    ("Unique Password Rule", "unique_passwords_per_site", "difficult_to_guess",
     "IF passwords are unique per site THEN a leak elsewhere doesn't make yours easy to guess."),

    # Authentication
    ("Two-Factor Rule", "two_factor_enabled", "extra_security_layer",
     "IF two-factor authentication is enabled THEN an extra security layer is added."),
    ("Biometric Rule", "biometric_auth_enabled", "strong_identity_verification",
     "IF biometric login is enabled THEN identity verification becomes much stronger."),
    ("Identity Verification Rule", "strong_identity_verification", "extra_security_layer",
     "IF identity verification is strong THEN it acts as an extra security layer."),
    ("Layered Security Rule", "extra_security_layer", "reduced_risk",
     "IF there is an extra security layer THEN the overall risk is reduced."),

    # Network
    ("Public Wi-Fi Rule", "public_wifi_used", "data_interception_risk",
     "IF public Wi-Fi is used THEN data interception risk increases."),
    ("VPN Rule", "vpn_used", "encrypted_traffic",
     "IF a VPN is used THEN traffic leaving the device is encrypted."),
    ("Encrypted Traffic Rule", "encrypted_traffic", "reduced_risk",
     "IF traffic is encrypted THEN interception risk is reduced overall."),
    ("Firewall Rule", "firewall_enabled", "blocked_unauthorized_traffic",
     "IF a firewall is enabled THEN unauthorized traffic is blocked."),
    ("Blocked Traffic Rule", "blocked_unauthorized_traffic", "reduced_risk",
     "IF unauthorized traffic is blocked THEN the overall risk is reduced."),
    ("HTTPS Rule", "https_used", "encrypted_in_transit",
     "IF a site uses HTTPS THEN the connection is encrypted in transit."),
    ("Transit Encryption Rule", "encrypted_in_transit", "reduced_risk",
     "IF data is encrypted in transit THEN interception is far less useful to an attacker."),
    ("Wi-Fi Encryption Rule", "strong_wifi_encryption", "network_protected",
     "IF a home network uses WPA2/WPA3 THEN it is protected from casual snooping."),
    ("Protected Network Rule", "network_protected", "reduced_risk",
     "IF the network is protected THEN the overall risk is reduced."),
    ("Outdated Software Rule", "outdated_software", "vulnerabilities_exposed",
     "IF software is not kept updated THEN known vulnerabilities remain exposed."),
    ("Exposed Vulnerability Rule", "vulnerabilities_exposed", "account_vulnerable",
     "IF vulnerabilities are exposed THEN the account/device becomes vulnerable."),

    # Malware & devices
    ("Antivirus Rule", "antivirus_installed", "malware_protected",
     "IF antivirus software is installed THEN the system is protected from malware."),
    ("Malware Protection Rule", "malware_protected", "reduced_risk",
     "IF the system is malware protected THEN the overall risk is reduced."),
    ("Update Rule", "software_updated", "vulnerabilities_patched",
     "IF software is kept updated THEN known vulnerabilities are patched."),
    ("Patched Vulnerability Rule", "vulnerabilities_patched", "reduced_risk",
     "IF vulnerabilities are patched THEN the overall risk is reduced."),
    ("Untrusted USB Rule", "usb_untrusted_used", "device_infected",
     "IF an unknown USB drive is used THEN the device may become infected."),
    ("Ransomware Rule", "ransomware_attack", "data_encrypted_by_attacker",
     "IF ransomware strikes THEN files get encrypted by the attacker."),
    ("Ransomware Loss Rule", "data_encrypted_by_attacker", "data_loss_risk",
     "IF an attacker has encrypted your files THEN there is a high risk of permanent data loss."),
    ("IoT Default Password Rule", "iot_default_password", "device_vulnerable",
     "IF a smart device keeps its default password THEN it is easy to compromise."),
    ("Vulnerable Device Rule", "device_vulnerable", "account_vulnerable",
     "IF a device is vulnerable THEN accounts and data reachable from it are also vulnerable."),

    # Data & privacy
    ("Encryption at Rest Rule", "data_encrypted", "data_protected_at_rest",
     "IF stored data is encrypted THEN it is protected at rest."),
    ("Data at Rest Rule", "data_protected_at_rest", "reduced_risk",
     "IF data is protected at rest THEN the overall risk is reduced."),
    ("Backup Rule", "regular_backups", "data_recoverable",
     "IF backups are taken regularly THEN data is recoverable after an incident."),
    ("Recoverability Rule", "data_recoverable", "reduced_risk",
     "IF data is recoverable THEN the impact of an incident - and the overall risk - is reduced."),
    ("No Backup Rule", "no_backups", "data_loss_risk",
     "IF there are no backups THEN one incident can cause permanent data loss."),
    ("Encrypted Messaging Rule", "encrypted_messaging_used", "private_communication",
     "IF messages are end-to-end encrypted THEN the conversation stays private."),
    ("Private Communication Rule", "private_communication", "reduced_risk",
     "IF communication is private THEN the overall risk of exposure is reduced."),
    ("App Permission Rule", "excessive_app_permissions", "privacy_exposed",
     "IF an app has excessive permissions THEN personal data is exposed to it."),
    ("Privacy Exposure Rule", "privacy_exposed", "data_theft_risk",
     "IF privacy is exposed THEN the risk of data theft increases."),

    # Social engineering
    ("Phishing Rule", "phishing_email_received", "credentials_at_risk",
     "IF a phishing email is received and acted upon THEN credentials are put at risk."),
    ("Vishing Rule", "social_engineering_call", "impersonation_risk",
     "IF a caller uses social engineering THEN there is a risk of successful impersonation."),
    ("Impersonation Rule", "impersonation_risk", "credentials_at_risk",
     "IF impersonation succeeds THEN credentials are put at risk."),
    ("Awareness Training Rule", "security_awareness_training", "spot_suspicious_messages",
     "IF someone has had security awareness training THEN they can spot suspicious messages."),
    ("Suspicion Rule", "spot_suspicious_messages", "credentials_protected",
     "IF suspicious messages are spotted early THEN credentials stay protected."),
    ("Credential Protection Rule", "credentials_protected", "reduced_risk",
     "IF credentials are protected THEN the overall risk is reduced."),

    # Mobile & physical
    ("Public Charging Rule", "public_charging_used", "juice_jacking_risk",
     "IF a public charging station is used THEN juice-jacking risk increases."),
    ("Juice Jacking Rule", "juice_jacking_risk", "data_theft_risk",
     "IF juice-jacking risk is present THEN there is a risk of data theft."),
    ("Unlocked Device Rule", "physical_device_unlocked", "unauthorized_physical_access",
     "IF a device is left unlocked THEN unauthorized physical access becomes possible."),
    ("Physical Access Rule", "unauthorized_physical_access", "account_vulnerable",
     "IF unauthorized physical access occurs THEN linked accounts become vulnerable."),

    # Planning
    ("Incident Plan Rule", "incident_response_plan", "faster_recovery",
     "IF there is an incident response plan THEN recovery from an incident is faster."),
    ("Faster Recovery Rule", "faster_recovery", "reduced_risk",
     "IF recovery is faster THEN the overall risk/impact is reduced."),
]
